### PR TITLE
Feat/tags

### PR DESCRIPTION
**Pull request by sgalkina**

### CODE REVIEW

**Comment by lyschoening** [comment]
Looks good...but I am not sure what tags are. Could you add a test that uses tags?

**Comment by sgalkina** [comment]
@lyschoening tags will be used to group endpoints by services they come from, right now schema collector put them all in one randomly ordered list

**Comment by lyschoening** [comment]
Tags would be useful, but that last commit looks strange. First, I think tags should be explicitly specified on the schema and not auto-generated; second, there needs to be a way of actually tagging operations (methods). The tag messages on the schema do not actually act as tags on the schema, but they are just descriptions of tags available to be used on the operations.

**Comment by lyschoening** [comment]
I think for the purposes of having a service that collects multiple schemas and combines them, it can just augment the schemas with the desired tags at that point, rather than tagging everything in advance.

**Comment by sgalkina** [comment]
@lyschoening yes true, reverted the last commit, this functionality will go to the schema collector service

**Comment by lyschoening** [comment]
What would still be needed here is a test case.

**Pull request merged**
